import {
  CardRegistry,
  cardId,
  isDomain,
  type CardDefinition,
  type Cost,
  type Domain,
} from '@riftbound/cards';

/**
 * Reads a card data file: a JSON array of card definitions.
 *
 * Card data is meant to be generated by an ingest step rather than written by
 * hand, and this is the boundary it comes through. It validates strictly and
 * reports every problem at once, because a silently mis-shaped card would
 * produce plausible-looking statistics that are quietly wrong.
 */
export class CardDataError extends Error {
  readonly problems: readonly string[];

  constructor(problems: readonly string[]) {
    super(`Card data is not usable:\n  ${problems.join('\n  ')}`);
    this.name = 'CardDataError';
    this.problems = problems;
  }
}

const CARD_TYPES = new Set(['legend', 'unit', 'spell', 'gear', 'rune', 'battlefield']);
const TIMINGS = new Set(['action', 'reaction']);
const MAX_REPORTED = 20;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function domainList(value: unknown, where: string, problems: string[]): Domain[] {
  if (value === undefined) {
    return [];
  }
  if (!Array.isArray(value)) {
    problems.push(`${where}: "domains" must be an array`);
    return [];
  }
  const domains: Domain[] = [];
  for (const entry of value) {
    if (typeof entry !== 'string' || !isDomain(entry)) {
      problems.push(`${where}: "${String(entry)}" is not a Domain`);
      continue;
    }
    domains.push(entry);
  }
  return domains;
}

function costOf(value: unknown, where: string, problems: string[]): Cost {
  if (!isRecord(value)) {
    problems.push(`${where}: "cost" must be an object like { "energy": 2, "power": ["fury"] }`);
    return { energy: 0, power: [] };
  }

  const energy = value['energy'];
  if (typeof energy !== 'number' || !Number.isInteger(energy) || energy < 0) {
    problems.push(`${where}: "cost.energy" must be a non-negative integer`);
  }

  const power = value['power'];
  const pips: Domain[] = [];
  if (power !== undefined) {
    if (!Array.isArray(power)) {
      problems.push(`${where}: "cost.power" must be an array of Domains`);
    } else {
      for (const pip of power) {
        if (typeof pip !== 'string' || !isDomain(pip)) {
          problems.push(`${where}: "${String(pip)}" is not a Domain in "cost.power"`);
          continue;
        }
        pips.push(pip);
      }
    }
  }

  return { energy: typeof energy === 'number' ? energy : 0, power: pips };
}

function stringList(value: unknown, where: string, field: string, problems: string[]): string[] {
  if (value === undefined) {
    return [];
  }
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string')) {
    problems.push(`${where}: "${field}" must be an array of strings`);
    return [];
  }
  return value as string[];
}

/** Parse and validate card data. Throws `CardDataError` listing every problem. */
export function parseCardsJson(text: string): CardDefinition[] {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new CardDataError([`Not valid JSON: ${detail}`]);
  }

  if (!Array.isArray(raw)) {
    throw new CardDataError(['Expected a JSON array of card definitions']);
  }

  const problems: string[] = [];
  const cards: CardDefinition[] = [];

  raw.forEach((entry, index) => {
    const where = `card ${index}`;
    if (!isRecord(entry)) {
      problems.push(`${where}: not an object`);
      return;
    }

    const id = entry['id'];
    const name = entry['name'];
    const type = entry['type'];
    const label = typeof id === 'string' && id !== '' ? `card ${index} (${id})` : where;

    if (typeof id !== 'string' || id === '') {
      problems.push(`${where}: "id" must be a non-empty string`);
    }
    if (typeof name !== 'string' || name === '') {
      problems.push(`${label}: "name" must be a non-empty string`);
    }
    if (typeof type !== 'string' || !CARD_TYPES.has(type)) {
      problems.push(`${label}: "${String(type)}" is not a card type`);
      return;
    }

    const domains = domainList(entry['domains'], label, problems);
    const cardText = entry['text'];
    if (cardText !== undefined && typeof cardText !== 'string') {
      problems.push(`${label}: "text" must be a string`);
    }
    const tags = stringList(entry['tags'], label, 'tags', problems);

    const base = {
      id: cardId(typeof id === 'string' ? id : `invalid-${index}`),
      name: typeof name === 'string' ? name : '',
      domains,
      text: typeof cardText === 'string' ? cardText : '',
      tags,
    };

    switch (type) {
      case 'legend': {
        const identity = domainList(entry['domainIdentity'], label, problems);
        if (identity.length === 0) {
          problems.push(`${label}: a Legend needs a non-empty "domainIdentity"`);
        }
        cards.push({ ...base, type: 'legend', domainIdentity: identity });
        return;
      }
      case 'unit': {
        const might = entry['might'];
        if (typeof might !== 'number' || !Number.isInteger(might) || might < 0) {
          problems.push(`${label}: "might" must be a non-negative integer`);
        }
        const champion = entry['champion'];
        if (champion !== undefined && typeof champion !== 'boolean') {
          problems.push(`${label}: "champion" must be a boolean`);
        }
        cards.push({
          ...base,
          type: 'unit',
          cost: costOf(entry['cost'], label, problems),
          might: typeof might === 'number' ? might : 0,
          champion: champion === true,
        });
        return;
      }
      case 'spell': {
        const timing = entry['timing'];
        if (typeof timing !== 'string' || !TIMINGS.has(timing)) {
          problems.push(`${label}: "timing" must be "action" or "reaction"`);
        }
        cards.push({
          ...base,
          type: 'spell',
          cost: costOf(entry['cost'], label, problems),
          timing: timing === 'reaction' ? 'reaction' : 'action',
        });
        return;
      }
      case 'gear': {
        cards.push({ ...base, type: 'gear', cost: costOf(entry['cost'], label, problems) });
        return;
      }
      case 'rune': {
        const domain = entry['domain'];
        if (typeof domain !== 'string' || !isDomain(domain)) {
          problems.push(`${label}: a Rune needs a "domain"`);
          return;
        }
        cards.push({
          ...base,
          type: 'rune',
          domains: domains.length > 0 ? domains : [domain],
          domain,
        });
        return;
      }
      case 'battlefield': {
        cards.push({ ...base, type: 'battlefield' });
        return;
      }
      default:
        problems.push(`${label}: unhandled card type "${type}"`);
    }
  });

  if (problems.length > 0) {
    const shown = problems.slice(0, MAX_REPORTED);
    if (problems.length > MAX_REPORTED) {
      shown.push(`... and ${problems.length - MAX_REPORTED} more`);
    }
    throw new CardDataError(shown);
  }

  return cards;
}

/** Parse card data and build the registry the rest of the tools read through. */
export function loadCardRegistry(text: string): CardRegistry {
  try {
    return CardRegistry.from(parseCardsJson(text));
  } catch (error) {
    if (error instanceof CardDataError) {
      throw error;
    }
    throw new CardDataError([error instanceof Error ? error.message : String(error)]);
  }
}
